export const ActionType = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    DETAIL_INC_DEC_ADD_TO_CART: 'DETAIL_INC_DEC_ADD_TO_CART',
    INC: "INC",
    DEC: "DEC",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
}